### ISSUE TITLE
Adding classes / custom Icons 

### ISSUE THREAD

**Issue by OlmoDalco** [canufeel/ember-leaflet-marker-cluster#13]
I would love to add classes or create custom icons for different marker-cluster-layers. I think this should be possible via the [markerClusterOptions(https://github.com/Leaflet/Leaflet.markercluster#options). However I have no Idea how to use them probably. Any chance to get an example?

**Comment by allthesignals** [comment]
A little late I guess, but it would look like this:
{{#marker-cluster-layer iconCreateFunction=iconCreateFunction}}
// your stuff
{{/marker-cluster-layer}}

and the controller:
iconCreateFunction: function(cluster) {
    // cluster.getChildCount()
    return L.icon({ iconUrl: '/images/icons/investments/cluster.png', iconSize: [41,41] });
  }
