### ISSUE TITLE
Fix breaking changes in FastBoot 1.0

### ISSUE THREAD

**Issue by simonihmig** [canufeel/ember-leaflet-marker-cluster#19]
The current `ember-cli-fastboot` releases (1.0.0-rc.1 and above) introduce breaking changes. These will most likely break your current FastBoot implementation.

See https://github.com/ember-fastboot/ember-cli-fastboot/issues/387 for more information and a guide on how to fix your addon. Also you may want to visit the `-fastboot` Slack channel to get help from other users.

*Note: this issue has been created automatically, by searching for certain patterns in your code. If you think this has been falsely created, feel free to close!*

**Comment by willviles** [comment]
If you'd like to publish `v0.1.2`, then this issue can be closed! 👍

**Comment by medokin** [comment]
@canufeel This seems fixed, can you publish a new release?

**Comment by The-Don-Himself** [comment]
Just another ping  
@canufeel

**Comment by canufeel** [comment]
@willviles @medokin @The-Don-Himself `v0.1.2` published

**Comment by The-Don-Himself** [comment]
That was real quick, thanks a ton!
