### ISSUE TITLE
index.js leaflet.markercluster has two different capitalisations of leaflet when importing.

### ISSUE THREAD

**Issue by mattedgar3** [canufeel/ember-leaflet-marker-cluster#2]
In index.js the directories where it is looking for markercluster are inconsistent
`  	app.import(app.bowerDirectory + '/Leaflet.markercluster/dist/leaflet.markercluster.js');
  	app.import(app.bowerDirectory + '/Leaflet.markercluster/dist/MarkerCluster.css');
  	app.import(app.bowerDirectory + '/leaflet.markercluster/dist/MarkerCluster.Default.css');`

The starting L in 'leaflet', two are capitalised and one is not.

**Comment by Palid** [comment]
Waiting for the commit to be merged!
