### ISSUE TITLE
Support for Leaflet.markercluster options

### ISSUE THREAD

**Issue by fpauser** [canufeel/ember-leaflet-marker-cluster#4]
Would be great if we could have all options from `Leaflet.markerCluster` (https://github.com/Leaflet/Leaflet.markercluster#options), including the `iconCreateFunction`, which should also be able to update the cluster-icon when a marker of this cluster was updated.

**Comment by batisteo** [comment]
:+1:

**Comment by canufeel** [comment]
3399f25 should fix this. Have a look

**Comment by canufeel** [comment]
@fpauser @batisteo Unfortunately i don't have any working project using this functionality for now. If anyone can confirm that it work, don't hesitate to write a comment and i will close this.

**Comment by fpauser** [comment]
Looks good to me - closed therefore.
