### ISSUE TITLE
Update for Leaflet 1.0 (ember-leaflet is already going there)

### ISSUE THREAD

**Issue by v3ss0n** [canufeel/ember-leaflet-marker-cluster#8]
Since ember-leaflet is upgrading , the most used ember-leaflet plugin need to  be updated too to latest marker cluster.

**Comment by canufeel** [comment]
@v3ss0n I totally agree. Any chance you can submit a PR for this? I don't currently have a real app where i can check that code still works with new versions.

**Comment by v3ss0n** [comment]
I will try in a while.

**Comment by localyost** [comment]
I updated to Leaflet 1.0 with one slight problem:

the Marker-Clustering doesnt seem to work with `PopupLayer` in EmberLeaflet

For now in `PopupLayer` I overrode the method `_addPopupListeners()` and added an undefined check at line 100

`let containerLayer = this.get('containerLayer');`
`const map = containerLayer._layer._map;`
` if(map){`
      `map.addEventListener('layerremove', this._onLayerRemove, this);`
` }`

**Comment by v3ss0n** [comment]
thanks a lot for testing @localyost

**Comment by techie55** [comment]
Hi,
I too am facing a compatibility issue with running ember-leaflet-marker-cluster with ember-leaflet 3.0.2. I get the following error:
Could not find module `ember-leaflet/mixins/container` imported from `ember-leaflet-marker-cluster/components/marker-cluster-layer`(…)

However, if I downgrade ember-leaflet to 2.2.7, it works. Any idea when the marker-cluster component will be upgraded?

**Comment by miguelcobain** [comment]
Some more info.
Since version `3.0.2` ember-leaflet no longer includes a `ContainerMixin`.
It now uses `ember-composability-tools` addon.
Changes: https://github.com/miguelcobain/ember-leaflet/commit/25ea9bb6f4cbbc84768c73150ff2a1e0c0dbe9aa

Maybe we should add an alias to ember-leaflet core so that layerSetup / layerTeardown keeps being called?

**Comment by techie55** [comment]
Hi Miguel,
Who can incorporate these changes into ember-leaflet-marker-cluster?
Thanks

**Comment by miguelcobain** [comment]
> Who can incorporate these changes into ember-leaflet-marker-cluster?

I think anyone can do that. Why not? :)

**Comment by v3ss0n** [comment]
awesome!! thanks a lot @fpauser  and @canufeel !
